---

stages:
  - test
  - release

lint:
  image: registry.gitlab.com/gitlab-org/gitlab-build-images:gitlab-charts-build-base
  stage: test
  script:
    - helm init --client-only
    - helm lint

release stable:
  stage: release
  script:
    - curl --request POST
            --form "token=$CI_JOB_TOKEN"
            --form ref=master
            --form "variables[CHART_NAME]=$CI_PROJECT_NAME"
            --form "variables[RELEASE_REF]=$CI_COMMIT_REF_NAME"
            https://gitlab.com/api/v4/projects/2860651/trigger/pipeline
  only:
    - /\Av[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?\Z/@gitlab-org/charts/elastic-stack
