fluentd-elasticsearch:
  image:
    repository: quay.io/fluentd_elasticsearch/fluentd
    tag: v2.8.0
    pullPolicy: IfNotPresent
    # pullSecrets:
    #   - myRegistrKeySecretName

  hostLogDir:
    varLog: /var/log
    dockerContainers: /var/lib/docker/containers
    libSystemdDir: /usr/lib64

  elasticsearch:
    auth:
      enabled: false
      user: "yourUser"
      password: "yourPass"
    bufferChunkLimit: "2M"
    bufferQueueLimit: 8
    host: "elasticsearch-master"
    logstashPrefix: "logstash"
    port: 9200
    path: ""
    scheme: "http"
    sslVerify: true
    sslVersion: "TLSv1_2"
    typeName: "_doc"
    logLevel: "info"
    logEs400Reason: false

elasticsearch:
  clusterName: "elasticsearch"
  nodeGroup: "master"
  masterService: ""

  roles:
    master: "true"
    ingest: "true"
    data: "true"

  replicas: 3
  minimumMasterNodes: 2

  image: "docker.elastic.co/elasticsearch/elasticsearch"
  imageTag: "7.6.2"
  imagePullPolicy: "IfNotPresent"

  esJavaOpts: "-Xmx1g -Xms1g"

  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: vsphere-sc
    resources:
      requests:
        storage: 30Gi

  persistence:
    enabled: true
    annotations: {}

  service:
    labels: {}
    labelsHeadless: {}
    type: ClusterIP
    nodePort: ""
    annotations: {}
    httpPortName: http
    transportPortName: transport
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
