apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.registry" . }}
  labels: {{- include "harbor.labels" . | nindent 4 }}
spec:
  ports:
    - name: registry
      port: 5000
    - name: controller
      port: 8080
  selector: {{- include "harbor.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: registry
