apiVersion: v1
description: Helm chart for deploying Istio gateways
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- ingressgateway
- gateways
name: istio-ingress
sources:
- http://github.com/istio/istio
version: 1.1.0
