apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ template "kuboard.fullname" . }}-user"
  labels:
{{ include "kuboard.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: "{{ template "kuboard.fullname" . }}-user"
    namespace: {{ .Release.Namespace }}
