apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.portal" . }}
  labels: {{- include "harbor.labels" . | nindent 4 }}
spec:
  {{- if (eq .Values.service.ingress.controller "gce") }}
  type: NodePort
  {{- end }}
  ports:
    - name: http
      port: 80
      targetPort: http
  selector: {{- include "harbor.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: portal
