{{- if eq .Values.service.type "Ingress" }}
{{- $ingress := .Values.service.ingress -}}
{{- $tls := .Values.service.tls -}}
{{- if eq .Values.service.ingress.controller "gce" }}
  {{- $_ := set . "portal_path" "/*" -}}
  {{- $_ := set . "api_path" "/api/*" -}}
  {{- $_ := set . "service_path" "/service/*" -}}
  {{- $_ := set . "v2_path" "/v2/*" -}}
  {{- $_ := set . "chartrepo_path" "/chartrepo/*" -}}
  {{- $_ := set . "controller_path" "/c/*" -}}
{{- else if eq .Values.service.ingress.controller "ncp" }}
  {{- $_ := set . "portal_path" "/" -}}
  {{- $_ := set . "api_path" "/api/.*" -}}
  {{- $_ := set . "service_path" "/service/.*" -}}
  {{- $_ := set . "v2_path" "/v2/.*" -}}
  {{- $_ := set . "chartrepo_path" "/chartrepo/.*" -}}
  {{- $_ := set . "controller_path" "/c/.*" -}}
{{- else }}
  {{- $_ := set . "portal_path" "/" -}}
  {{- $_ := set . "api_path" "/api/" -}}
  {{- $_ := set . "service_path" "/service/" -}}
  {{- $_ := set . "v2_path" "/v2/" -}}
  {{- $_ := set . "chartrepo_path" "/chartrepo/" -}}
  {{- $_ := set . "controller_path" "/c/" -}}
{{- end }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "harbor.ingress" . }}
  labels: {{- include "harbor.labels" . | nindent 4 }}
  {{- if $ingress.annotations }}
  annotations: {{- toYaml $ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if $tls.enabled }}
  tls:
    {{- if $tls.secretName }}
    - secretName: {{ $tls.secretName }}
    {{- else }}
    - secretName: {{ include "harbor.ingress" . }}
    {{- end }}
      {{- if $ingress.hosts.core }}
      hosts:
        - {{ $ingress.hosts.core }}
      {{- end }}
    {{- if .Values.notary.enabled }}
    {{- if $tls.notarySecretName }}
    - secretName: "{{ $tls.notarySecretName }}"
    {{- else if $tls.secretName }}
    - secretName: "{{ $tls.secretName }}"
    {{- else }}
    - secretName: "{{ template "harbor.ingress" . }}"
    {{- end }}
      {{- if $ingress.hosts.notary }}
      hosts:
        - {{ $ingress.hosts.notary }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if eq .Values.service.ingress.controller "ncp" }}
  backend:
    serviceName: {{ include "harbor.portal" . }}
    servicePort: http
  {{- end }}
  rules:
    - http:
        paths:
          - path: {{ .portal_path }}
            backend:
              serviceName: {{ include "harbor.portal" . }}
              servicePort: http
          - path: {{ .api_path }}
            backend:
              serviceName: {{ include "harbor.core" . }}
              servicePort: http
          - path: {{ .service_path }}
            backend:
              serviceName: {{ include "harbor.core" . }}
              servicePort: http
          - path: {{ .v2_path }}
            backend:
              serviceName: {{ include "harbor.core" . }}
              servicePort: http
          - path: {{ .chartrepo_path }}
            backend:
              serviceName: {{ include "harbor.core" . }}
              servicePort: http
          - path: {{ .controller_path }}
            backend:
              serviceName: {{ include "harbor.core" . }}
              servicePort: http
      {{- if $ingress.hosts.core }}
      host: {{ $ingress.hosts.core }}
      {{- end }}
    {{- if .Values.notary.enabled }}
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "harbor.notary-server" . }}
              servicePort: notary-server
      {{- if $ingress.hosts.notary }}
      host: {{ $ingress.hosts.notary }}
      {{- end }}
    {{- end }}
{{- end }}
