apiVersion: v1
appVersion: 9.4.1
description: GitLab Community Edition
home: https://about.gitlab.com
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.png
keywords:
- git
- gitlab
- ci
name: gitlab-ce
sources:
- https://hub.docker.com/r/gitlab/gitlab-ce/
- https://docs.gitlab.com/omnibus/
version: 0.2.2
