{{- if not .Values.useHelm3 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubeapps.tiller-proxy.fullname" . }}
  labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    app: {{ template "kubeapps.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.tillerProxy.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "kubeapps.tiller-proxy.fullname" . }}
    release: {{ .Release.Name }}
{{- end }}{{/* matches useHelm3 */}}
