{{- if not .Values.useHelm3 -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kubeapps.tiller-proxy.fullname" . }}
  labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    app: {{ template "kubeapps.tiller-proxy.fullname" . }}
spec:
  replicas: {{ .Values.tillerProxy.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "kubeapps.tiller-proxy.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kubeapps.tiller-proxy.fullname" . }}
        app.kubernetes.io/name: {{ template "kubeapps.name" . }}
        release: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "kubeapps.tiller-proxy.fullname" . }}
      # Increase termination timeout to let remaining operations to finish before killing the pods
      # This is because new releases/upgrades/deletions are synchronous operations
      terminationGracePeriodSeconds: 300
{{- include "kubeapps.imagePullSecrets" . | indent 6 }}
      {{- if .Values.tillerProxy.affinity }}
      affinity: {{- include "kubeapps.tplValue" (dict "value" .Values.tillerProxy.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tillerProxy.nodeSelector }}
      nodeSelector: {{- include "kubeapps.tplValue" (dict "value" .Values.tillerProxy.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tillerProxy.tolerations }}
      tolerations: {{- include "kubeapps.tplValue" (dict "value" .Values.tillerProxy.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      containers:
        - name: proxy
          image: {{ template "kubeapps.image" (list .Values.tillerProxy.image .Values.global) }}
          command:
            - /proxy
          args:
            - --host={{ .Values.tillerProxy.host }}
            - --user-agent-comment=kubeapps/{{ .Chart.AppVersion }}
            - --assetsvc-url=http://{{ template "kubeapps.assetsvc.fullname" . }}:{{ .Values.assetsvc.service.port }}
            {{- if .Values.tillerProxy.tls }}
            - --tls
            {{- if .Values.tillerProxy.tls.verify }}
            - --tls-verify
            {{- end }}
            {{- if .Values.tillerProxy.timeout }}
            - --timeout={{ .Values.tillerProxy.timeout }}
            {{- end }}
            {{- end }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.tillerProxy.tls }}
            - name: HELM_HOME
              value: /etc/certs
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.tillerProxy.service.port }}
          {{- if .Values.tillerProxy.livenessProbe }}
          livenessProbe: {{- toYaml .Values.tillerProxy.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.tillerProxy.readinessProbe }}
          readinessProbe: {{- toYaml .Values.tillerProxy.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.tillerProxy.resources }}
          resources: {{- toYaml .Values.tillerProxy.resources | nindent 12 }}
          {{- end }}
      {{- if .Values.tillerProxy.tls }}
          volumeMounts:
            - name: tiller-certs
              mountPath: /etc/certs
      volumes:
        - name: tiller-certs
          secret:
            secretName: {{ template "kubeapps.tiller-proxy.fullname" . }}
      {{- end }}
{{- end }}{{/* matches useHelm3 */}}
