{{- if not .Values.useHelm3 -}}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "kubeapps.tiller-proxy.fullname" . }}
  labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    app: {{ template "kubeapps.tiller-proxy.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - "kubeapps.com"
    resources:
      - apprepositories
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "kubeapps.tiller-proxy.fullname" . }}
  labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    app: {{ template "kubeapps.tiller-proxy.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "kubeapps.tiller-proxy.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kubeapps.tiller-proxy.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- if .Values.allowNamespaceDiscovery }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "kubeapps:controller:tiller-proxy-ns-discovery-{{ .Release.Namespace }}"
  labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    app: {{ template "kubeapps.tiller-proxy.fullname" . }}
rules:
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "kubeapps:controller:tiller-proxy-ns-discovery-{{ .Release.Namespace }}"
  labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    app: {{ template "kubeapps.tiller-proxy.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "kubeapps:controller:tiller-proxy-ns-discovery-{{ .Release.Namespace }}"
subjects:
  - kind: ServiceAccount
    name: {{ template "kubeapps.tiller-proxy.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
{{- if .Values.allowNamespaceDiscovery }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "kubeapps:controller:tiller-proxy-operators-{{ .Release.Namespace }}"
  labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    app: {{ template "kubeapps.tiller-proxy.fullname" . }}
rules:
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "kubeapps:controller:tiller-proxy-operators-{{ .Release.Namespace }}"
  labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    app: {{ template "kubeapps.tiller-proxy.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "kubeapps:controller:tiller-proxy-operators-{{ .Release.Namespace }}"
subjects:
  - kind: ServiceAccount
    name: {{ template "kubeapps.tiller-proxy.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
{{- end }}{{/* matches useHelm3 */}}
