{{- if not .Values.useHelm3 -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubeapps.tiller-proxy.fullname" . }}
  labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    app: {{ template "kubeapps.tiller-proxy.fullname" . }}
{{- end }}{{/* matches useHelm3 */}}
