{{- if .Values.notary.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "harbor.notary-server" . }}
  labels: {{- include "harbor.labels" . | nindent 4 }}
    component: notary-server
spec:
  replicas: {{ .Values.notary.server.replicas }}
  selector:
    matchLabels: {{- include "harbor.matchLabels" . | nindent 6 }}
      component: notary-server
  template:
    metadata:
      labels: {{- include "harbor.labels" . | nindent 8 }}
        component: notary-server
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/notary/notary-secret.yaml") . | sha256sum }}
        checksum/secret-core: {{ include (print $.Template.BasePath "/core/core-secret.yaml") . | sha256sum }}
        {{- if .Values.notary.podAnnotations }}
        annotations: {{- include "harbor.tplValue" (dict "value" .Values.notary.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
    spec:
{{- include "harbor.imagePullSecrets" . | indent 6 }}
      {{- if .Values.notary.affinity }}
      affinity: {{- include "harbor.tplValue" (dict "value" .Values.notary.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.notary.nodeSelector }}
      nodeSelector: {{- include "harbor.tplValue" (dict "value" .Values.notary.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.notary.tolerations }}
      tolerations: {{- include "harbor.tplValue" (dict "value" .Values.notary.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      containers:
        - name: notary-server
          image: "{{ template "harbor.notaryServerImage" . }}"
          imagePullPolicy: {{ .Values.notaryServerImage.pullPolicy | quote }}
          {{- if .Values.notary.server.resources }}
          resources: {{- toYaml .Values.notary.server.resources | nindent 12 }}
          {{- end }}
          env:
            - name: BITNAMI_DEBUG
              value: {{ ternary "true" "false" .Values.notaryServerImage.debug | quote }}
            - name: MIGRATIONS_PATH
              value: migrations/server/postgresql
            - name: DB_URL
              value: {{ include "harbor.database.notaryServer" . }}
          volumeMounts:
            - name: notary-config
              mountPath: /etc/notary
            - name: root-certificate
              mountPath: /root.crt
              subPath: tls.crt
            {{- if .Values.notary.secretName }}
            - name: notary-ca
              mountPath: /etc/ssl/notary/cert/notary-signer-ca.crt
              subPath: ca
            {{- end }}
          ports:
            - containerPort: 4443
              name: notary-server
      volumes:
        - name: notary-config
          secret:
            secretName: {{ include "harbor.notary-server" . }}
        - name: root-certificate
          secret:
            {{- if .Values.core.secretName }}
            secretName: {{ .Values.core.secretName }}
            {{- else }}
            secretName: {{ include "harbor.core" . }}
            {{- end }}
        {{- if .Values.notary.secretName }}
        - name: notary-ca
          secret:
            secretName: {{ .Values.notary.secretName }}
        {{- end }}
{{- end }}
