apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jenkins.fullname" . }}
  labels: {{- include "jenkins.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.jenkinsPassword }}
  jenkins-password: {{ default "" .Values.jenkinsPassword | b64enc | quote }}
  {{- else }}
  jenkins-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
