{{- if .Values.notary.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "harbor.notary-signer" . }}
  labels: {{- include "harbor.labels" . | nindent 4 }}
    component: notary-signer
spec:
  replicas: {{ .Values.notary.signer.replicas }}
  selector:
    matchLabels: {{- include "harbor.matchLabels" . | nindent 6 }}
      component: notary-signer
  template:
    metadata:
      labels: {{- include "harbor.labels" . | nindent 8 }}
        component: notary-signer
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/notary/notary-secret.yaml") . | sha256sum }}
        {{- if .Values.notary.podAnnotations }}
        annotations: {{- include "harbor.tplValue" (dict "value" .Values.notary.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
    spec:
{{- include "harbor.imagePullSecrets" . | indent 6 }}
      {{- if .Values.notary.affinity }}
      affinity: {{- include "harbor.tplValue" (dict "value" .Values.notary.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.notary.nodeSelector }}
      nodeSelector: {{- include "harbor.tplValue" (dict "value" .Values.notary.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.notary.tolerations }}
      tolerations: {{- include "harbor.tplValue" (dict "value" .Values.notary.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      containers:
        - name: notary-signer
          image: {{ include "harbor.notarySignerImage" . }}
          imagePullPolicy: {{ .Values.notarySignerImage.pullPolicy | quote }}
          {{- if .Values.notary.signer.resources }}
          resources: {{- toYaml .Values.notary.signer.resources | nindent 12 }}
          {{- end }}
          env:
            - name: BITNAMI_DEBUG
              value: {{ ternary "true" "false" .Values.notarySignerImage.debug | quote }}
            - name: MIGRATIONS_PATH
              value: migrations/signer/postgresql
            - name: DB_URL
              value: "{{ template "harbor.database.notarySigner" . }}"
            - name: NOTARY_SIGNER_DEFAULTALIAS
              value: defaultalias
          volumeMounts:
            - name: notary-config
              mountPath: /etc/notary
            {{- if .Values.notary.secretName }}
            - name: notary-cert
              mountPath: /etc/ssl/notary/cert/notary-signer-ca.crt
              subPath: ca
            - name: notary-cert
              mountPath: /etc/ssl/notary/cert/notary-signer.crt
              subPath: crt
            - name: notary-cert
              mountPath: /etc/ssl/notary/cert/notary-signer.key
              subPath: key
            {{- end }}
      volumes:
        - name: notary-config
          secret:
            secretName: {{ include "harbor.notary-server" . }}
        {{- if .Values.notary.secretName }}
        - name: notary-cert
          secret:
            secretName: {{ .Values.notary.secretName }}
        {{- end }}
{{- end }}
