{{- if .Values.notary.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor.notary-server" . }}
  labels: {{- include "harbor.labels" . | nindent 4 }}
    component: notary
data:
  {{- if not .Values.notary.secretName }}
  {{ $ca := genCA "harbor-notary-ca" 365 }}
  {{ $cert := genSignedCert (include "harbor.notary-signer" .) nil nil 365 $ca }}
  notary-signer-ca.crt: {{ $ca.Cert | b64enc | quote }}
  notary-signer.crt: {{ $cert.Cert | b64enc | quote }}
  notary-signer.key: {{ $cert.Key | b64enc | quote }}
  {{- end }}
  server-config.postgres.json: {{ tpl (.Files.Get "conf/notary-server.json") . | b64enc }}
  signer-config.postgres.json: {{ tpl (.Files.Get "conf/notary-signer.json") . | b64enc }}
{{- end }}
