apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab.fullname" . }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
    app.kubernetes.io/component: gitlab
spec:
  type: {{ .Values.gitlab.service.type }}
  ports:
    - name: http
      targetPort: http
      port: {{ .Values.gitlab.service.http.port }}
      protocol: TCP
    - name: ssh
      targetPort: ssh
      port: {{ .Values.gitlab.service.ssh.port }}
      protocol: TCP
  selector:
    {{- include "gitlab.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gitlab

