{{- if .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "gitlab.fullname" . }}-redis
spec:
  accessModes:
  - {{ .Values.redis.persistence.accessMode }}
  storageClassName: {{ .Values.redis.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}
