apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gitlab.fullname" . }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
type: Opaque
data:
  dbUser: {{ .Values.gitlab.env.db.user | b64enc | quote }}
  dbPassword: {{ .Values.gitlab.env.db.pass | b64enc | quote }}

  dbKeyBase: {{ .Values.gitlab.env.secrets.dbKeyBase | b64enc | quote }}
  secretKeyBase: {{ .Values.gitlab.env.secrets.secretKeyBase | b64enc | quote }}
  otpKeyBase: {{ .Values.gitlab.env.secrets.otpKeyBase | b64enc | quote }}

  rootPassword: {{ .Values.gitlab.env.rootPassword | b64enc | quote }}

  awsAccessKeyId: {{ .Values.gitlab.env.awsAccessKeyId | b64enc | quote }}
  awsSecretAccessKey: {{ .Values.gitlab.env.awsSecretAccessKey | b64enc | quote }}

  {{ if ne .Values.gitlab.env.artifactsObjectStore.connection.aws.accessKeyId "" -}}
  artifactsObjectStoreConnectionAwsAccessKeyId: {{ .Values.gitlab.env.artifactsObjectStore.connection.aws.accessKeyId | b64enc | quote }}
  {{- else -}}
  artifactsObjectStoreConnectionAwsAccessKeyId: {{ .Values.gitlab.env.awsAccessKeyId | b64enc | quote }}
  {{- end }}
  {{ if ne .Values.gitlab.env.artifactsObjectStore.connection.aws.secretAccessKey "" -}}
  artifactsObjectStoreConnectionAwsSecretAccessKey: {{ .Values.gitlab.env.artifactsObjectStore.connection.aws.secretAccessKey | b64enc | quote }}
  {{- else -}}
  artifactsObjectStoreConnectionAwsSecretAccessKey: {{ .Values.gitlab.env.awsSecretAccessKey | b64enc | quote }}
  {{- end }}

  {{ if ne .Values.gitlab.env.lfs.store.connection.aws.accessKeyID "" -}}
  lfsStoreConnectionAwsAccessKeyId: {{ .Values.gitlab.env.lfs.store.connection.aws.accessKeyId | b64enc | quote }}
  {{- else -}}
  lfsStoreConnectionAwsAccessKeyId: {{ .Values.gitlab.env.awsAccessKeyId | b64enc | quote }}
  {{- end }}
  {{ if ne .Values.gitlab.env.lfs.store.connection.aws.secretAccessKey "" -}}
  lfsStoreConnectionAwsSecretAccessKey: {{ .Values.gitlab.env.lfs.store.connection.aws.secretAccessKey | b64enc | quote }}
  {{- else -}}
  lfsStoreConnectionAwsSecretAccessKey: {{ .Values.gitlab.env.awsSecretAccessKey | b64enc | quote }}
  {{- end }}

  {{ if ne .Values.gitlab.env.uploads.objectStore.connection.aws.accessKeyID "" -}}
  uploadsObjectStoreConnectionAwsAccessKeyId: {{ .Values.gitlab.env.uploads.objectStore.connection.aws.accessKeyId | b64enc | quote }}
  {{- else -}}
  uploadsObjectStoreConnectionAwsAccessKeyId: {{ .Values.gitlab.env.awsAccessKeyId | b64enc | quote }}
  {{- end }}
  {{ if ne .Values.gitlab.env.uploads.objectStore.connection.aws.secretAccessKey "" -}}
  uploadsObjectStoreConnectionAwsSecretAccessKey: {{ .Values.gitlab.env.uploads.objectStore.connection.aws.secretAccessKey | b64enc | quote }}
  {{- else -}}
  uploadsObjectStoreConnectionAwsSecretAccessKey: {{ .Values.gitlab.env.awsSecretAccessKey | b64enc | quote }}
  {{- end }}

  {{ if ne .Values.gitlab.env.smtp.user "" -}}
  smtpUser: {{ .Values.gitlab.env.smtp.user | b64enc | quote }}
  {{- else -}}
  smtpUser: ''
  {{- end }}
  {{ if ne .Values.gitlab.env.smtp.password "" -}}
  smtpPassword: {{ .Values.gitlab.env.smtp.password | b64enc | quote }}
  {{- else -}}
  smtpPassword: ''
  {{- end }}

  {{ if ne .Values.gitlab.env.imap.user "" -}}
  imapUser: {{ .Values.gitlab.env.imap.user | b64enc | quote }}
  {{- else -}}
  imapUser: ''
  {{- end }}
  {{ if ne .Values.gitlab.env.imap.pass "" -}}
  imapPass: {{ .Values.gitlab.env.imap.pass | b64enc | quote }}
  {{- else -}}
  imapPass: ''
  {{- end }}

  {{ if ne .Values.gitlab.env.ldap.bindDn "" -}}
  ldapBindDn: {{ .Values.gitlab.env.ldap.bindDn | b64enc | quote -}}
  {{- else -}}
  ldapBindDn: ''
  {{- end }}
  {{ if ne .Values.gitlab.env.ldap.pass "" -}}
  ldapPass: {{ .Values.gitlab.env.ldap.pass | b64enc | quote }}
  {{- else -}}
  ldapPass: ''
  {{- end }}

  {{ if ne .Values.gitlab.env.oauth.google.apiKey "" -}}
  oauthGoogleApiKey: {{ .Values.gitlab.env.oauth.google.apiKey | b64enc | quote }}
  {{- else -}}
  oauthGoogleApiKey: ''
  {{- end }}
  {{ if ne .Values.gitlab.env.oauth.google.appSecret "" -}}
  oauthGoogleAppSecret: {{ .Values.gitlab.env.oauth.google.appSecret | b64enc | quote }}
  {{- else -}}
  oauthGoogleAppSecret: ''
  {{- end }}

  {{ if ne .Values.gitlab.env.oauth.facebook.apiKey "" -}}
  oauthFacebookApiKey: {{ .Values.gitlab.env.oauth.facebook.apiKey | b64enc | quote }}
  {{- else -}}
  oauthFacebookApiKey: ''
  {{- end }}
  {{ if ne .Values.gitlab.env.oauth.facebook.appSecret "" -}}
  oauthFacebookAppSecret: {{ .Values.gitlab.env.oauth.facebook.appSecret | b64enc | quote }}
  {{- else -}}
  oauthFacebookAppSecret: ''
  {{- end }}

  {{ if ne .Values.gitlab.env.oauth.twitter.apiKey "" -}}
  oauthTwitterApiKey: {{ .Values.gitlab.env.oauth.twitter.apiKey | b64enc | quote }}
  {{- else -}}
  oauthTwitterApiKey: ''
  {{- end }}
  {{ if ne .Values.gitlab.env.oauth.twitter.appSecret "" -}}
  oauthTwitterAppSecret: {{ .Values.gitlab.env.oauth.twitter.appSecret | b64enc | quote }}
  {{- else -}}
  oauthTwitterAppSecret: ''
  {{- end }}

  {{ if ne .Values.gitlab.env.oauth.authentiq.client.id "" -}}
  oauthAuthentiqClientId: {{ .Values.gitlab.env.oauth.authentiq.client.id | b64enc | quote }}
  {{- else -}}
  oauthAuthentiqClientId: ''
  {{- end }}
  {{ if ne .Values.gitlab.env.oauth.authentiq.client.secret "" -}}
  oauthAuthentiqClientSecret: {{ .Values.gitlab.env.oauth.authentiq.client.secret | b64enc | quote }}
  {{- else -}}
  oauthAuthentiqClientSecret: ''
  {{- end }}

  {{ if ne .Values.gitlab.env.oauth.github.apiKey "" -}}
  oauthGithubApiKey: {{ .Values.gitlab.env.oauth.github.apiKey | b64enc | quote }}
  {{- else -}}
  oauthGithubApiKey: ''
  {{- end }}
  {{ if ne .Values.gitlab.env.oauth.github.appSecret "" -}}
  oauthGithubAppSecret: {{ .Values.gitlab.env.oauth.github.appSecret | b64enc | quote }}
  {{- else -}}
  oauthGithubAppSecret: ''
  {{- end }}

  {{ if ne .Values.gitlab.env.oauth.gitlab.apiKey "" -}}
  oauthGitlabApiKey: {{ .Values.gitlab.env.oauth.gitlab.apiKey | b64enc | quote }}
  {{- else -}}
  oauthGitlabApiKey: ''
  {{- end }}
  {{ if ne .Values.gitlab.env.oauth.gitlab.appSecret "" -}}
  oauthGitlabAppSecret: {{ .Values.gitlab.env.oauth.gitlab.appSecret | b64enc | quote }}
  {{- else -}}
  oauthGitlabAppSecret: ''
  {{- end }}

  {{ if ne .Values.gitlab.env.oauth.bitbucket.apiKey "" -}}
  oauthBitbucketApiKey: {{ .Values.gitlab.env.oauth.bitbucket.apiKey | b64enc | quote }}
  {{- else -}}
  oauthBitbucketApiKey: ''
  {{- end }}
  {{ if ne .Values.gitlab.env.oauth.bitbucket.appSecret "" -}}
  oauthBitbucketAppSecret: {{ .Values.gitlab.env.oauth.bitbucket.appSecret | b64enc | quote }}
  {{- else -}}
  oauthBitbucketAppSecret: ''
  {{- end }}

  {{ if ne .Values.gitlab.env.oauth.saml.idpCertFingerprint "" -}}
  oauthSamlIdpCertFingerprint: {{ .Values.gitlab.env.oauth.saml.idpCertFingerprint | b64enc | quote }}
  {{- else -}}
  oauthSamlIdpCertFingerprint: ''
  {{- end }}

  {{ if ne .Values.gitlab.env.oauth.crowd.app.name "" -}}
  oauthCrowdAppName: {{ .Values.gitlab.env.oauth.crowd.app.name | b64enc | quote }}
  {{- else -}}
  oauthCrowdAppName: ''
  {{- end }}
  {{ if ne .Values.gitlab.env.oauth.crowd.app.password "" -}}
  oauthCrowdAppPassword: {{ .Values.gitlab.env.oauth.crowd.app.password | b64enc | quote }}
  {{- else -}}
  oauthCrowdAppPassword: ''
  {{- end }}

  {{ if ne .Values.gitlab.env.oauth.auth0.client.id "" -}}
  oauthAuth0ClientId: {{ .Values.gitlab.env.oauth.auth0.client.id | b64enc | quote }}
  {{- else -}}
  oauthAuth0ClientId: ''
  {{- end }}
  {{ if ne .Values.gitlab.env.oauth.auth0.client.secret "" -}}
  oauthAuth0ClientSecret: {{ .Values.gitlab.env.oauth.auth0.client.secret | b64enc | quote }}
  {{- else -}}
  oauthAuth0ClientSecret: ''
  {{- end }}

  {{ if ne .Values.gitlab.env.oauth.azure.api.key "" -}}
  oauthAzureApiKey: {{ .Values.gitlab.env.oauth.azure.api.key | b64enc | quote }}
  {{- else -}}
  oauthAzureApiKey: ''
  {{- end }}
  {{ if ne .Values.gitlab.env.oauth.azure.api.secret "" -}}
  oauthAzureApiSecret: {{ .Values.gitlab.env.oauth.azure.api.secret | b64enc | quote }}
  {{- else -}}
  oauthAzureApiSecret: ''
  {{- end }}
  {{ if ne .Values.gitlab.env.oauth.azure.tenantId "" -}}
  oauthAzureTenantId: {{ .Values.gitlab.env.oauth.azure.tenantId | b64enc | quote }}
  {{- else -}}
  oauthAzureTenantId: ''
  {{- end }}

  {{ if ne .Values.gitlab.env.oauth2.generic.app.id "" -}}
  oauth2GenericAppId: {{ .Values.gitlab.env.oauth2.generic.app.id | b64enc | quote }}
  {{- else -}}
  oauth2GenericAppId: ''
  {{- end }}
  {{ if ne .Values.gitlab.env.oauth2.generic.app.secret "" -}}
  oauth2GenericAppSecret: {{ .Values.gitlab.env.oauth2.generic.app.secret | b64enc | quote }}
  {{- else -}}
  oauth2GenericAppSecret: ''
  {{- end }}

  {{ if ne .Values.gitlab.env.awsBackups.acesssKeyId "" -}}
  awsBackupsAcesssKeyId: {{ .Values.gitlab.env.awsBackups.acesssKeyId | b64enc | quote }}
  {{- else -}}
  awsBackupsAcesssKeyId: ''
  {{- end }}
  {{ if ne .Values.gitlab.env.awsBackups.secretAccessKey "" -}}
  awsBackupsSecretAccessKey: {{ .Values.gitlab.env.awsBackups.secretAccessKey | b64enc | quote }}
  {{- else -}}
  awsBackupsSecretAccessKey: ''
  {{- end }}

  {{ if ne .Values.gitlab.env.gcsBackups.accessKeyId "" -}}
  gcsBackupsAccessKeyId: {{ .Values.gitlab.env.gcsBackups.accessKeyId | b64enc | quote }}
  {{- else -}}
  gcsBackupsAccessKeyId: ''
  {{- end }}
  {{ if ne .Values.gitlab.env.gcsBackups.secretAccessKey "" -}}
  gcsBackupsSecretAccessKey: {{ .Values.gitlab.env.gcsBackups.secretAccessKey | b64enc | quote }}
  {{- else -}}
  gcsBackupsSecretAccessKey: ''
  {{- end }}
