apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.jobservice" . }}
  labels: {{- include "harbor.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector: {{- include "harbor.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: jobservice
