{{- if .Values.chartmuseum.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor.chartmuseum" . }}
  labels: {{- include "harbor.labels" . | nindent 4 }}
    app.kubernetes.io/component: chartmuseum
spec:
  ports:
    - port: 80
      name: http
      targetPort: http
  selector: {{- include "harbor.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: chartmuseum
{{- end }}
