appVersion: 1.12.0
description: A Helm chart for the Weave Scope cluster visualizer node agent.
home: https://www.weave.works/oss/scope/
icon: https://avatars1.githubusercontent.com/u/9976052?s=64
keywords:
- containers
- dashboard
- monitoring
maintainers:
- email: github@orion-com.com
  name: omkensey
name: weave-scope-agent
sources:
- https://github.com/weaveworks/scope
version: 1.1.10
