apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor.core" . }}
  labels: {{- include "harbor.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secretKey }}
  secretKey: {{ .Values.secretKey | b64enc | quote }}
  {{- else if (not .Values.forcePassword) }}
  secretKey: {{ randAlphaNum 16 | b64enc | quote }}
  {{- else }}
  secretKey: {{ required "A secret key is required!" .Values.secretKey }}
  {{- end }}

  {{- if .Values.core.secret }}
  secret: {{ .Values.core.secret | b64enc | quote }}
  {{- else if (not .Values.forcePassword) }}
  secret: {{ randAlphaNum 16 | b64enc | quote }}
  {{- else }}
  secret: {{ required "A secret is required!" .Values.core.secret }}
  {{- end }}

  {{- if not .Values.core.secretName }}
  tls.crt: {{ .Files.Get "cert/tls.crt" | b64enc }}
  tls.key: {{ .Files.Get "cert/tls.key" | b64enc }}
  {{- end }}
