{{- if .Values.persistence.enabled }}
{{- $registry := .Values.persistence.persistentVolumeClaim.registry -}}
{{- if and (not $registry.existingClaim) (eq .Values.persistence.imageChartStorage.type "filesystem") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "harbor.registry" . }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
  labels: {{- include "harbor.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
spec:
  accessModes:
    - {{ $registry.accessMode }}
  resources:
    requests:
      storage: {{ $registry.size }}
  {{ include "harbor.registry.storageClass" . }}
{{- end }}
{{- end }}
