apiVersion: v1
appVersion: 1.10.2
description: Harbor is an an open source trusted cloud native registry project that
  stores, signs, and scans content
engine: gotpl
home: https://goharbor.io/
icon: https://bitnami.com/assets/stacks/harbor-core/img/harbor-core-stack-220x234.png
keywords:
- docker
- registry
- vulnerability
- scan
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: harbor
sources:
- https://github.com/bitnami/bitnami-docker-harbor-core
- https://github.com/bitnami/bitnami-docker-harbor-portal
- https://github.com/bitnami/bitnami-docker-harbor-jobservice
- https://github.com/bitnami/bitnami-docker-harbor-registry
- https://github.com/bitnami/bitnami-docker-harbor-registryctl
version: 5.0.8
